# Generated by Django 6.0.4 on 2026-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
